name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name : export api key to validate
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name : Exports api key to env
        run: export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
       
      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
