name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Inject API Key and Build
      run: |
        echo "import os" > inject_api_key.py
        echo "file_path = 'git_narrate/ai_narrator.py'" >> inject_api_key.py
        echo "with open(file_path, 'r') as f: content = f.read()" >> inject_api_key.py
        echo "content = content.replace('__OPENAI_API_KEY_PLACEHOLDER__', os.environ.get('OPENAI_API_KEY', ''))" >> inject_api_key.py
        echo "with open(file_path, 'w') as f: f.write(content)" >> inject_api_key.py
        echo "print('API Key injected into ' + file_path)" >> inject_api_key.py
        
        python inject_api_key.py
        python -m build
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
